# Generated by Django 5.1 on 2025-05-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(max_length=255)),
                ('enjoyed_subjects', models.CharField(max_length=255)),
                ('excited_subjects', models.CharField(max_length=255)),
                ('dream_job', models.CharField(max_length=255)),
                ('fees_budget', models.CharField(max_length=255)),
                ('college_location', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('twelfth_score', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
