# Generated by Django 5.1 on 2025-05-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='ai_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
