# Generated by Django 5.1 on 2025-09-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_studentdetail_ai_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdetail',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentdetail',
            name='college_location',
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='preferred_locations',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='enjoyed_subjects',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='excited_subjects',
            field=models.JSONField(default=list),
        ),
    ]
