# Generated by Django 5.1 on 2025-09-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_stream', models.CharField(blank=True, max_length=100, null=True)),
                ('enjoyed_subject', models.CharField(blank=True, max_length=100, null=True)),
                ('exciting_subject', models.CharField(blank=True, max_length=100, null=True)),
                ('dream_job', models.CharField(blank=True, max_length=100, null=True)),
                ('fees_budget', models.CharField(blank=True, max_length=100, null=True)),
                ('college_location', models.CharField(blank=True, max_length=100, null=True)),
                ('student_name', models.CharField(blank=True, max_length=30, null=True)),
                ('student_12th_score_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('email_id', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('student_location', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
