# Generated by Django 5.1 on 2026-06-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_alter_admissioncutoff_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='inst_type',
            field=models.CharField(blank=True, choices=[('govt_gia', 'Government / GIA'), ('self_finance', 'Self-Finance')], default='', help_text='Institute type: govt_gia, self_finance', max_length=30),
        ),
    ]
