# Generated by Django 6.0.2 on 2026-02-17 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('infra_labs_score', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('infra_sports_score', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('infra_premises_score', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('extra_curricular_score', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('patent_score', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('alumni_score', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('faculty_research_score', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('faculty_experience_score', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('placement_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('average_package', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('curriculum_score', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='predictor.university')),
            ],
            options={
                'unique_together': {('university', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AdmissionCutoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2025)),
                ('category', models.CharField(max_length=50)),
                ('board', models.CharField(blank=True, max_length=50, null=True)),
                ('opening_rank', models.FloatField(blank=True, null=True)),
                ('closing_rank', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutoffs', to='predictor.course')),
            ],
            options={
                'unique_together': {('course', 'year', 'category', 'board')},
            },
        ),
    ]
