# Generated by Django 5.1 on 2026-03-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infra_weight', models.IntegerField(default=15, help_text='Weight % for infrastructure score')),
                ('course_weight', models.IntegerField(default=30, help_text='Weight % for course score')),
                ('extra_curricular_weight', models.IntegerField(default=10, help_text='Weight % for extra-curricular')),
                ('patent_weight', models.IntegerField(default=10, help_text='Weight % for patent score')),
                ('fees_weight', models.IntegerField(default=15, help_text='Weight % for fees score')),
                ('alumni_weight', models.IntegerField(default=10, help_text='Weight % for alumni score')),
                ('degree_weight', models.IntegerField(default=10, help_text='Weight % for degree score')),
                ('tolerance', models.IntegerField(default=50, help_text='Rank buffer — how close to closing rank counts as Possible')),
                ('safe_multiplier', models.IntegerField(default=2, help_text='Ranks below (closing - tolerance * safe_multiplier) are Safe')),
                ('stretch_multiplier', models.IntegerField(default=10, help_text='Ranks above (closing + tolerance * stretch_multiplier) are excluded')),
            ],
            options={
                'verbose_name': 'Score Weight Configuration',
                'verbose_name_plural': 'Score Weight Configuration',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='degree_score',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Score for the degree level (B.Tech, M.Tech, Diploma, etc.)', max_digits=5),
        ),
        migrations.AddField(
            model_name='university',
            name='mode',
            field=models.CharField(choices=[('regular', 'Regular'), ('distance', 'Distance'), ('both', 'Both')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='university',
            name='state',
            field=models.CharField(blank=True, help_text='Indian state, e.g. Gujarat, Maharashtra', max_length=100, null=True),
        ),
    ]
