# Generated by Django 5.1 on 2026-04-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_scoreweight_course_degree_score_university_mode_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='admissioncutoff',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='admissioncutoff',
            name='round',
            field=models.IntegerField(choices=[(1, 'Round 1'), (2, 'Round 2'), (3, 'Round 3')], default=1, help_text='ACPC admission round (1, 2, or 3)'),
        ),
        migrations.AddField(
            model_name='university',
            name='inst_type',
            field=models.CharField(blank=True, choices=[('govt', 'Government'), ('gia', 'Grant-in-Aid'), ('self_finance', 'Self-Finance'), ('private', 'Private')], default='', help_text='Institute type: govt, gia, self_finance, private', max_length=30),
        ),
        migrations.AlterField(
            model_name='admissioncutoff',
            name='board',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='admissioncutoff',
            unique_together={('course', 'year', 'round', 'category', 'board')},
        ),
        migrations.AddIndex(
            model_name='admissioncutoff',
            index=models.Index(fields=['round'], name='predictor_a_round_0a0eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='admissioncutoff',
            index=models.Index(fields=['year', 'round'], name='predictor_a_year_e5db05_idx'),
        ),
    ]
